baseurl = "https://large-government-of-canada-it-projects.github.io/"
languageCode = "en-us"
title = "Large Government of Canada IT projects"
googleAnalytics = "UA-159391141-1"

[params]
  author = "Ottawa Civic Tech"
  description = "A list and dataset of Government of Canada IT projects over $1 million, based on data from 2016 and 2019. Sortable by department, by total cost, and estimated completion date."

# Thanks to
# https://discourse.gohugo.io/t/lodash-template-tags-are-escaped-since-hugo-0-19/6299/4
[mediaTypes."text/template"]
  suffixes = ["ejs"]

[outputFormats.EJS]
  mediaType = "text/template"
  isHTML = true
  isPlainText = true

# Thanks to
# https://discourse.gohugo.io/t/raw-html-getting-omitted-in-0-60-0/22032/2
[markup.goldmark.renderer]
  unsafe = true
